# Generated by Django 3.2.12 on 2026-03-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sector_industrial', models.CharField(max_length=100)),
                ('domicilio', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_empleados', models.IntegerField(default=0)),
                ('estructura_organizativa', models.CharField(max_length=100)),
                ('tipo_iva', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
                ('socios', models.CharField(max_length=100)),
            ],
        ),
    ]
