# Generated by Django 3.2.12 on 2026-03-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
    ]
